### ISSUE TITLE
error "uninitialized constant Zeebe::Client::GatewayProtocol::ListWorkflowsRequest (NameError)"

### ISSUE THREAD

**Issue by maxivak** [zeebe-io/zeebe-client-ruby#55]
I am getting an error when running demo script `examples/demo.rb`

```
uninitialized constant Zeebe::Client::GatewayProtocol::ListWorkflowsRequest (NameError)
```

**Comment by cmur2** [comment]
Hi, sorry for the inconvenience - some functionality used by the demo script has been removed in https://github.com/zeebe-io/zeebe/issues/1935

I updated the script in https://github.com/zeebe-io/zeebe-client-ruby/commit/952d51145dba6e365a7d24ea85778366b6929824 on master to work again, thanks for reporting!
