### ISSUE TITLE
Usage with Camunda Cloud?

### ISSUE THREAD

**Issue by amutz** [zeebe-io/zeebe-client-ruby#82]
Does zeeb-client-ruby support connecting to Camunda Cloud?  I'm trying to figure out how to use it with Oauth credentials, and from the documentation, I don't see how to do it.

Is this supported and I just can't figure out how to do it?  Or is it not currently supported?

Thank you.

**Comment by cmur2** [comment]
Hi, I did not look into compatibility with Camunda Cloud as this client predates it. I also don't know how to make it work on the spot but happy to look at any PRs :)
